package com.seuprojeto.mulheres_inspiradoras;
import java.util.List;

import org.springframework.stereotype.Service;

import java.util.Arrays;

@Service
public class MulheresService {
	public List<Mulher> listarMulheres(){
		return Arrays.asList(
				 new Mulher("Ada Lovelace", "Computação", "A imaginação é a faculdade da descoberta."),
				  new Mulher("Marie Curie", "Ciência", "Nada na vida deve ser temido, apenas compreendido."),
				  new Mulher("Frida Kahlo", "Arte", "Pinto a mim mesma porque sou sozinha."),
				  new Mulher("Malala Yousafzai", "Educação", "Um livro, uma caneta, uma criança e um professor podem mudar o mundo."),
				  new Mulher("Amelia Earhart", "Aviação", "O mais difícil é decidir agir; o resto é mera tenacidade."),
				  new Mulher("Rosa Parks", "Direitos Civis", "Nunca seja limitado pelo que outros pensam que você pode fazer."),
				  new Mulher("Cleópatra", "História", "Eu não sou obrigada a nada, exceto a ser grande."),
				  new Mulher("Simone de Beauvoir", "Filosofia", "Não se nasce mulher: torna-se mulher."),
				  new Mulher("Serena Williams", "Esporte", "O sucesso não é sobre vencer os outros, é sobre vencer a si mesmo."),
				  new Mulher("Chimamanda Ngozi Adichie", "Literatura", "Não devemos aceitar que a história das mulheres seja contada pelos homens."),
				  new Mulher("Wangari Maathai", "Meio Ambiente", "É preciso acreditar que podemos fazer a diferença."),
				  new Mulher("Sally Ride", "Astronomia", "A ciência não é apenas para homens ou mulheres, é para todos."),
				  new Mulher("Oprah Winfrey", "Empreendedorismo", "Transforme sua vida em uma história que você se orgulha de contar."),
				  new Mulher("Virginia Woolf", "Literatura", "Não se pode encontrar paz evitando a vida."),
				  new Mulher("Hedy Lamarr", "Inovação", "As pessoas acham que a beleza é uma distração, mas é um presente."),
				  new Mulher("Jane Goodall", "Biologia", "O que você faz faz a diferença, e você precisa decidir que tipo de diferença quer fazer."),
				  new Mulher("Eleanor Roosevelt", "Direitos Humanos", "Ninguém pode fazer você se sentir inferior sem o seu consentimento."),
				  new Mulher("Billie Jean King", "Esporte", "A vida é sobre lutar pelo que é certo, não pelo que é fácil."),
				  new Mulher("Margaret Hamilton", "Computação", "Nós fazemos o impossível todos os dias."),
				  new Mulher("Rachel Carson", "Meio Ambiente", "O homem é parte da natureza, e não sua dominadora."),
				  new Mulher("Mary Shelley", "Literatura", "A vida começa quando nos atrevermos a ir além do conhecido."),
				  new Mulher("Katherine Johnson", "Matemática", "Nós vamos fazer o que for necessário para chegar à meta."),
				  new Mulher("Florence Nightingale", "Saúde", "Eu atribuo meu sucesso à disciplina e à paixão pelo que faço."),
				  new Mulher("Maya Angelou", "Literatura", "Você pode encontrar muitas derrotas, mas nunca deve ser derrotado."),
				  new Mulher("Indira Gandhi", "Política", "A honestidade e a coragem são minha força."),
				  new Mulher("Billie Holiday", "Música", "Se você não tem nada a dizer, faça com que sua música fale."),
				  new Mulher("Mother Teresa", "Humanitarismo", "Não podemos fazer grandes coisas, apenas pequenas coisas com grande amor."),
				  new Mulher("Coco Chanel", "Moda", "A melhor cor do mundo é aquela que fica bem em você."),
				  new Mulher("Simone Biles", "Esporte", "Não importa o quão difícil seja, continue se levantando."),
				  new Mulher("Margaret Atwood", "Literatura", "A esperança é um subversivo."),
				  new Mulher("Ruth Bader Ginsburg", "Direito", "Lute pelo que você acredita, mesmo que isso seja difícil."),
				  new Mulher("Harriet Tubman", "Direitos Civis", "Eu nunca deixei o medo me parar."),
				  new Mulher("Anne Frank", "Escrita", "Mesmo nas piores situações, ainda há bondade."),
				  new Mulher("Gloria Steinem", "Feminismo", "O poder não é dado, é conquistado."),
				  new Mulher("Louise Bourgeois", "Arte", "A dor é criativa."),
				  new Mulher("Angela Merkel", "Política", "A liderança é servir aos outros."),
				  new Mulher("Wangari Maathai", "Meio Ambiente", "Plante árvores e semeie esperança."),
				  new Mulher("Billie Eilish", "Música", "Seja você mesmo e ninguém poderá tirar isso de você."),
				  new Mulher("Serena Williams", "Esporte", "Eu aprendi a não temer o fracasso."),
				  new Mulher("Malala Yousafzai", "Educação", "Um livro, uma caneta podem mudar o mundo."),
				  new Mulher("Ada Lovelace", "Computação", "A imaginação é a faculdade da descoberta."),
				  new Mulher("Marie Curie", "Ciência", "Nada na vida deve ser temido, apenas compreendido."),
				  new Mulher("Frida Kahlo", "Arte", "Pinto a mim mesma porque sou sozinha."),
				  new Mulher("Amelia Earhart", "Aviação", "O mais difícil é decidir agir; o resto é mera tenacidade."),
				  new Mulher("Rosa Parks", "Direitos Civis", "Nunca seja limitado pelo que outros pensam que você pode fazer."),
				  new Mulher("Cleópatra", "História", "Eu não sou obrigada a nada, exceto a ser grande."),
				  new Mulher("Simone de Beauvoir", "Filosofia", "Não se nasce mulher: torna-se mulher."),
				  new Mulher("Chimamanda Ngozi Adichie", "Literatura", "Não devemos aceitar que a história das mulheres seja contada pelos homens."),
				  new Mulher("Wangari Maathai", "Meio Ambiente", "É preciso acreditar que podemos fazer a diferença."),
				  new Mulher("Sally Ride", "Astronomia", "A ciência não é apenas para homens ou mulheres, é para todos."),
				  new Mulher("Oprah Winfrey", "Empreendedorismo", "Transforme sua vida em uma história que você se orgulha de contar."),
				  new Mulher("Virginia Woolf", "Literatura", "Não se pode encontrar paz evitando a vida."),
				  new Mulher("Hedy Lamarr", "Inovação", "As pessoas acham que a beleza é uma distração, mas é um presente."),
				  new Mulher("Jane Goodall", "Biologia", "O que você faz faz a diferença, e você precisa decidir que tipo de diferença quer fazer."),
				  new Mulher("Eleanor Roosevelt", "Direitos Humanos", "Ninguém pode fazer você se sentir inferior sem o seu consentimento."),
				  new Mulher("Billie Jean King", "Esporte", "A vida é sobre lutar pelo que é certo, não pelo que é fácil."),
				  new Mulher("Margaret Hamilton", "Computação", "Nós fazemos o impossível todos os dias."),
				  new Mulher("Rachel Carson", "Meio Ambiente", "O homem é parte da natureza, e não sua dominadora."),
				  new Mulher("Mary Shelley", "Literatura", "A vida começa quando nos atrevermos a ir além do conhecido."),
				  new Mulher("Katherine Johnson", "Matemática", "Nós vamos fazer o que for necessário para chegar à meta."),
				  new Mulher("Florence Nightingale", "Saúde", "Eu atribuo meu sucesso à disciplina e à paixão pelo que faço."),
				  new Mulher("Maya Angelou", "Literatura", "Você pode encontrar muitas derrotas, mas nunca deve ser derrotado."),
				  new Mulher("Indira Gandhi", "Política", "A honestidade e a coragem são minha força."),
				  new Mulher("Billie Holiday", "Música", "Se você não tem nada a dizer, faça com que sua música fale."),
				  new Mulher("Mother Teresa", "Humanitarismo", "Não podemos fazer grandes coisas, apenas pequenas coisas com grande amor."),
				  new Mulher("Coco Chanel", "Moda", "A melhor cor do mundo é aquela que fica bem em você."),
				  new Mulher("Simone Biles", "Esporte", "Não importa o quão difícil seja, continue se levantando."),
				  new Mulher("Margaret Atwood", "Literatura", "A esperança é um subversivo."),
				  new Mulher("Ruth Bader Ginsburg", "Direito", "Lute pelo que você acredita, mesmo que isso seja difícil."),
				  new Mulher("Harriet Tubman", "Direitos Civis", "Eu nunca deixei o medo me parar."),
				  new Mulher("Anne Frank", "Escrita", "Mesmo nas piores situações, ainda há bondade."),
				  new Mulher("Gloria Steinem", "Feminismo", "O poder não é dado, é conquistado."),
				  new Mulher("Louise Bourgeois", "Arte", "A dor é criativa."),
				  new Mulher("Angela Merkel", "Política", "A liderança é servir aos outros."),
				  new Mulher("Ada Yonath", "Ciência", "A perseverança é o caminho para grandes descobertas."),
				  new Mulher("Toni Morrison", "Literatura", "Se você quer voar, você tem que abrir suas asas."),
				  new Mulher("Valentina Tereshkova", "Astronomia", "A coragem é a essência da conquista."),
				  new Mulher("Mae Jemison", "Astronomia", "Nunca se limite pelo que você vê."),
				  new Mulher("Ella Fitzgerald", "Música", "O impossível é apenas uma opinião."),
				  new Mulher("Sheryl Sandberg", "Tecnologia", "O que você fizer importa, e você deve fazê-lo com coragem."),
				  new Mulher("Billie Eilish", "Música", "Ser diferente é a melhor coisa que você pode ser."),
				  new Mulher("Jane Austen", "Literatura", "Não há charme igual à bondade do coração."),
				  new Mulher("Laverne Cox", "Ativismo", "Ser visível é ser poderoso."),
				  new Mulher("Rachel Maddow", "Jornalismo", "A verdade é a arma mais forte que existe."),
				  new Mulher("Ada Yonath", "Ciência", "A perseverança é o caminho para grandes descobertas."),
				  new Mulher("Wangari Maathai", "Meio Ambiente", "Se você tem uma visão, lute por ela."),
				  new Mulher("Katherine Johnson", "Matemática", "O céu não é o limite."),
				  new Mulher("Rigoberta Menchú", "Direitos Humanos", "A educação é a chave da liberdade."),
				  new Mulher("Lina Bo Bardi", "Arquitetura", "A arte está em todos os lugares."),
				  new Mulher("Isabel Allende", "Literatura", "A vida é feita de histórias que nos transformam."),
				  new Mulher("Ada Lovelace", "Computação", "A imaginação é a faculdade da descoberta.")
				);
				
	}
}
